/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container': '#f0edef',
        error: '#ba1a1a',
        'on-tertiary-container': '#6a8b7b',
        secondary: '#755b00',
        'on-background': '#1b1b1d',
        'on-tertiary-fixed': '#012115',
        'error-container': '#ffdad6',
        'on-primary-container': '#79849b',
        'surface-container-highest': '#e4e2e3',
        'on-surface-variant': '#45474c',
        'primary-fixed-dim': '#bbc7df',
        'tertiary-fixed-dim': '#accebc',
        'on-primary-fixed-variant': '#3c475b',
        'on-secondary-container': '#785d00',
        'on-secondary': '#ffffff',
        'surface-dim': '#dcd9db',
        outline: '#75777d',
        'primary-fixed': '#d7e3fc',
        'on-error-container': '#93000a',
        'surface-bright': '#fbf8fa',
        'tertiary-fixed': '#c7ebd7',
        tertiary: '#000000',
        surface: '#fbf8fa',
        'tertiary-container': '#101c2e',
        'secondary-fixed-dim': '#e6c364',
        'surface-container-low': '#f5f3f5',
        'on-secondary-fixed': '#241a00',
        'inverse-on-surface': '#f3f0f2',
        'secondary-container': '#fed977',
        primary: '#101c2e',
        'on-primary-fixed': '#101c2e',
        'secondary-fixed': '#ffe08f',
        'inverse-primary': '#bbc7df',
        background: '#fbf8fa',
        'on-surface': '#1b1b1d',
        'on-primary': '#ffffff',
        'inverse-surface': '#303032',
        'surface-tint': '#535f74',
        'on-tertiary-fixed-variant': '#2e4d3f',
        'surface-variant': '#e4e2e3',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#584400',
        'surface-container-high': '#eae7e9',
        'on-error': '#ffffff',
        'primary-container': '#101c2e',
        'outline-variant': '#c5c6cd',
        terracotta: '#ba4a1a',
        'deep-green': '#1a4a3a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-md': '24px',
        'stack-lg': '48px',
        'margin-mobile': '20px',
        base: '8px',
        'stack-sm': '12px',
        gutter: '24px',
        'margin-desktop': '64px',
        'container-max': '1280px',
      },
      fontFamily: {
        'body-md': ['"Source Sans 3"', 'sans-serif'],
        'price-display': ['Manrope', 'sans-serif'],
        'label-md': ['Manrope', 'sans-serif'],
        'body-lg': ['"Source Sans 3"', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'headline-lg-mobile': ['Manrope', 'sans-serif'],
        'display-lg': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'price-display': ['20px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
